ALTER TABLE TB_ESTADO ADD CONSTRAINT pkTB_ESTADO PRIMARY KEY(SIGLA_ESTADO);
ALTER TABLE TB_CLASSE ADD CONSTRAINT pkTB_CLASSE PRIMARY KEY(ID_CLASSE);
ALTER TABLE TB_ALUNO ADD CONSTRAINT pkTB_ALUNO PRIMARY KEY(COD_ALUNO);
ALTER TABLE TB_PROFESSOR ADD CONSTRAINT pkTB_PROFESSOR PRIMARY KEY(ID_PROFESSOR);
ALTER TABLE TB_DISCIPLINA ADD CONSTRAINT pkTB_DISCIPLINA PRIMARY KEY(ID_DISCIPLINA);

ALTER TABLE TB_ALUNO ADD CONSTRAINT FK_TB_ALUNO_TB_ESTADO FOREIGN KEY(SIGLA_ESTADO) REFERENCES TB_ESTADO(SIGLA_ESTADO);
ALTER TABLE TB_ALUNO ADD CONSTRAINT FK_TB_ALUNO_TB_CLASSE FOREIGN KEY(ID_CLASSE) REFERENCES TB_CLASSE(ID_CLASSE);
ALTER TABLE TB_DISCIPLINA ADD CONSTRAINT FK_TB_DISCIPLINA_TB_PROFESSOR FOREIGN KEY(ID_PROFESSOR_DISCIPLINA) REFERENCES TB_PROFESSOR(ID_PROFESSOR);
ALTER TABLE TB_ALUNO_DISCIPLINA ADD CONSTRAINT FK_TB_ALUNO_DISCIPLINA_TB_ALUNO FOREIGN KEY(COD_ALUNO) REFERENCES TB_ALUNO(COD_ALUNO);
ALTER TABLE TB_ALUNO_DISCIPLINA ADD CONSTRAINT FK_TB_ALUNO_DISCIPLINA_TB_DISCIPLINA FOREIGN KEY(ID_DISCIPLINA) REFERENCES TB_DISCIPLINA(ID_DISCIPLINA);
ALTER TABLE TB_ALUNO_DISCIPLINA ADD CONSTRAINT pkTB_ALUNO_DISCIPLINA PRIMARY KEY(COD_ALUNO, ID_DISCIPLINA);