SELECT NOME_ALUNO, ID_CLASSE FROM TB_ALUNO
ORDER BY NOME_ALUNO;

SELECT NOME_ALUNO, ID_CLASSE FROM TB_ALUNO
ORDER BY COD_ALUNO DESC;

SELECT A.COD_ALUNO 
FROM TB_ALUNO A
INNER JOIN TB_ALUNO_DISCIPLINA B
ON A.COD_ALUNO=B.COD_ALUNO
INNER JOIN TB_DISCIPLINA C
ON C.ID_DISCIPLINA=B.ID_DISCIPLINA
WHERE C.NOME_DISCIPLINA='MATEMATICA'
AND A.COD_ALUNO IN (
			SELECT A.COD_ALUNO 
			FROM TB_ALUNO A
			INNER JOIN TB_ALUNO_DISCIPLINA B
			ON A.COD_ALUNO=B.COD_ALUNO
			INNER JOIN TB_DISCIPLINA C
			ON C.ID_DISCIPLINA=B.ID_DISCIPLINA
			WHERE C.NOME_DISCIPLINA='PORTUGUES');


SELECT A.COD_ALUNO FROM TB_ALUNO A 
INNER JOIN TB_ALUNO_DISCIPLINA AD1
ON A.COD_ALUNO = AD1.COD_ALUNO 
INNER JOIN TB_ALUNO_DISCIPLINA AD2
ON A.COD_ALUNO = AD2.COD_ALUNO 
WHERE AD1.ID_DISCIPLINA ='POR' 
    AND AD2.ID_DISCIPLINA ='MAT';