SELECT Alu.NOME_ALUNO, Alu.ID_CLASSE, Dis.NOME_DISCIPLINA FROM TB_ALUNO Alu
INNER JOIN TB_ALUNO_DISCIPLINA AluDi
ON Alu.COD_ALUNO=AluDi.COD_ALUNO
INNER JOIN TB_DISCIPLINA Dis
ON Dis.ID_DISCIPLINA=AluDi.ID_DISCIPLINA
WHERE Dis.NOME_DISCIPLINA='PORTUGUES' OR Dis.NOME_DISCIPLINA='MATEMATICA';

SELECT Alu.NOME_ALUNO, Alu.END_ALUNO, Dis.NOME_DISCIPLINA FROM TB_ALUNO Alu
INNER JOIN TB_ALUNO_DISCIPLINA AluDi
ON Alu.COD_ALUNO=AluDi.COD_ALUNO
INNER JOIN TB_DISCIPLINA Dis
ON Dis.ID_DISCIPLINA=AluDi.ID_DISCIPLINA
WHERE Dis.NOME_DISCIPLINA='FISICA';

SELECT Alu.NOME_ALUNO, Alu.END_ALUNO, Dis.NOME_DISCIPLINA, Cla.ID_ANDAR FROM TB_ALUNO Alu
INNER JOIN TB_ALUNO_DISCIPLINA AluDi
ON Alu.COD_ALUNO=AluDi.COD_ALUNO
INNER JOIN TB_DISCIPLINA Dis
ON Dis.ID_DISCIPLINA=AluDi.ID_DISCIPLINA
INNER JOIN TB_CLASSE Cla
ON Cla.ID_CLASSE=Alu.ID_CLASSE
WHERE Dis.NOME_DISCIPLINA='FISICA';





