ALTER TABLE Predio ADD CONSTRAINT pkPredio PRIMARY KEY(CodPred);

ALTER TABLE Sala ADD CONSTRAINT FK_SALA_RELATION_PREDIO FOREIGN KEY(CodPred) REFERENCES Predio(CodPred);
ALTER TABLE Sala ADD CONSTRAINT pkSala PRIMARY KEY(NumSala, CodPred);

ALTER TABLE Titulacao ADD CONSTRAINT pkTitulacao PRIMARY KEY(CodTit);

ALTER TABLE Depto ADD CONSTRAINT pkCodDepto PRIMARY KEY(CodDepto);

ALTER TABLE Professor ADD CONSTRAINT pkProfessor PRIMARY KEY(CodProf);
ALTER TABLE Professor ADD CONSTRAINT FK_PROFESSOR_RELATION_DEPTO FOREIGN KEY(CodDepto) REFERENCES Depto(CodDepto);
ALTER TABLE Professor ADD CONSTRAINT FK_PROFESSOR_RELATION_TITULACAO FOREIGN KEY(CodTit) REFERENCES Titulacao(CodTit);

ALTER TABLE Disciplina ADD CONSTRAINT FK_DISCIPLI_RELATION_DEPTO FOREIGN KEY(CodDepto) REFERENCES Depto(CodDepto);
ALTER TABLE Disciplina ADD CONSTRAINT pkDisciplina PRIMARY KEY(NumDisc, CodDepto);

ALTER TABLE PreReq ADD CONSTRAINT FK_PREREQ_TEM_PRE_DISCIPLI FOREIGN KEY(NumDisc, CodDepto) REFERENCES Disciplina(NumDisc, CodDepto);
ALTER TABLE PreReq ADD CONSTRAINT FK_PREREQ_EH_PRE_DISCIPLI FOREIGN KEY(NumDiscPreReq, CodDeptoPreReq) REFERENCES Disciplina(NumDisc, CodDepto);
ALTER TABLE PreReq ADD CONSTRAINT pkPreReq PRIMARY KEY(CodDeptoPreReq, NumDiscPreReq, CodDepto, NumDisc);

ALTER TABLE Turma ADD CONSTRAINT FK_TURMA_RELATION_DISCIPLI FOREIGN KEY(NumDisc, CodDepto) REFERENCES Disciplina(NumDisc, CodDepto);
ALTER TABLE Turma ADD CONSTRAINT pkTurma PRIMARY KEY(AnoSem, CodDepto, NumDisc, SiglaTur);

ALTER TABLE ProfTurma ADD CONSTRAINT FK_PROFTURM_PROFTURMA_PROFESSOR FOREIGN KEY(CodProf) REFERENCES Professor(CodProf);
ALTER TABLE ProfTurma ADD CONSTRAINT FK_PROFTURM_PROFTURMA_TURMA FOREIGN KEY(AnoSem, CodDepto, NumDisc, SiglaTur) REFERENCES Turma(AnoSem, CodDepto, NumDisc, SiglaTur);
ALTER TABLE ProfTurma ADD CONSTRAINT pkProfTurma PRIMARY KEY(CodProf, CodDepto, NumDisc, AnoSem, SiglaTur);

ALTER TABLE Horario ADD CONSTRAINT FK_HORARIO_RELATION_TURMA FOREIGN KEY(AnoSem, CodDepto, NumDisc, SiglaTur) REFERENCES Turma(AnoSem, CodDepto, NumDisc, SiglaTur);
ALTER TABLE Horario ADD CONSTRAINT FK_HORARIO_RELATION_SALA FOREIGN KEY(CodPred, NumSala) REFERENCES Sala(CodPred, NumSala);
ALTER TABLE Horario ADD CONSTRAINT pkHorario PRIMARY KEY(AnoSem, CodDepto, NumDisc, SiglaTur, DiaSem, HoraInicio);
