USE users_projects

ALTER TABLE users
DROP CONSTRAINT UQ__users__F3DBC572613BDDA3

ALTER TABLE users
ALTER COLUMN username VARCHAR(10) NOT NULL 

ALTER TABLE users
ADD CONSTRAINT UQ_username UNIQUE (username)

ALTER TABLE users
ALTER COLUMN passwordd VARCHAR(8)  NOT NULL 
